version: "3"
services:
  postgres:
    image: postgres:10.5
    container_name: postgres
    env_file:
      - docker.env
    volumes:
      - ./postgres:/var/lib/postgresql/data
    network_mode: bridge
  react_on_rails_app:
    image: react_on_rails
    build: ../
    container_name: react_on_rails
    command: app
    env_file:
      - docker.env
    volumes:
      - ./log:/var/www/app/log
    ports:
      - "3000:8080"
    links:
      - postgres
    network_mode: bridge

